<<<<<<< Updated upstream
# Generated by Django 4.1.5 on 2023-01-17 07:30

from django.db import migrations, models
=======
# Generated by Django 4.1.5 on 2023-02-09 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
>>>>>>> Stashed changes


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< Updated upstream
            name='Doctor',
            fields=[
                ('fname', models.CharField(help_text='First Name of Doctor', max_length=255, verbose_name='First Name')),
                ('lname', models.CharField(help_text='Last Name of Doctor', max_length=255, verbose_name='Last Name')),
                ('uname', models.CharField(help_text='Username of Doctor', max_length=255, primary_key=True, serialize=False, verbose_name='Username')),
                ('email', models.EmailField(help_text='eMail to contact you for notifications', max_length=254, verbose_name='eMail')),
                ('pwd', models.CharField(help_text='Password', max_length=255, verbose_name='Password')),
=======
            name='Account',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=60, primary_key=True, serialize=False, verbose_name='eMail')),
                ('username', models.CharField(max_length=255, verbose_name='Username')),
                ('password', models.CharField(max_length=255)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('fname', models.CharField(max_length=255, verbose_name='First Name')),
                ('lname', models.CharField(max_length=255, verbose_name='Last Name')),
                ('uname', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Username')),
                ('email', models.EmailField(max_length=254, verbose_name='eMail')),
                ('pwd', models.CharField(max_length=255, verbose_name='Password')),
>>>>>>> Stashed changes
            ],
            options={
                'ordering': ['lname', 'fname'],
            },
        ),
        migrations.CreateModel(
            name='Pharmacist',
            fields=[
<<<<<<< Updated upstream
                ('fname', models.CharField(help_text='First Name of Doctor', max_length=255, verbose_name='First Name')),
                ('lname', models.CharField(help_text='Last Name of Doctor', max_length=255, verbose_name='Last Name')),
                ('uname', models.CharField(help_text='Username of Doctor', max_length=255, primary_key=True, serialize=False, verbose_name='Username')),
                ('clinic', models.CharField(help_text='First Name of Doctor', max_length=255, verbose_name='First Name')),
                ('email', models.EmailField(help_text='eMail to contact you for notifications', max_length=254, verbose_name='eMail')),
                ('pwd', models.CharField(help_text='Password', max_length=255, verbose_name='Password')),
=======
                ('fname', models.CharField(max_length=255, verbose_name='First Name')),
                ('lname', models.CharField(max_length=255, verbose_name='Last Name')),
                ('uname', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Username')),
                ('clinic', models.CharField(max_length=255, verbose_name='Clinic')),
                ('email', models.EmailField(max_length=254, verbose_name='eMail')),
                ('pwd', models.CharField(max_length=255, verbose_name='Password')),
>>>>>>> Stashed changes
            ],
            options={
                'ordering': ['lname', 'fname', 'clinic'],
            },
        ),
<<<<<<< Updated upstream
=======
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='duser',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accountforms.doctor'),
        ),
        migrations.AddField(
            model_name='account',
            name='puser',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accountforms.pharmacist'),
        ),
>>>>>>> Stashed changes
    ]
