# Generated by Django 4.1.6 on 2023-02-11 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('accountforms', '0001_initial'), ('accountforms', '0002_alter_pharmacist_options_remove_account_puser_and_more'), ('accountforms', '0003_account_puser'), ('accountforms', '0004_alter_doctor_options_remove_account_duser_and_more'), ('accountforms', '0005_account_duser'), ('accountforms', '0006_order_alter_doctor_email_delete_message'), ('accountforms', '0007_alter_order_reciever')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True, verbose_name='eMail')),
                ('doctorid', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='name')),
            ],
            options={
                'ordering': ['email', 'doctorid'],
            },
        ),
        migrations.CreateModel(
            name='Pharmacist',
            fields=[
                ('clinic', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='name')),
            ],
            options={
                'ordering': ['email', 'clinic'],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=60, primary_key=True, serialize=False, verbose_name='eMail')),
                ('username', models.CharField(max_length=255, verbose_name='Username')),
                ('password', models.CharField(max_length=255)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('puser', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accountforms.pharmacist')),
                ('duser', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accountforms.doctor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientid', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True, null=True)),
                ('reciever', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reciever', to='accountforms.pharmacist')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sender', 'reciever'],
            },
        ),
    ]
