# Generated by Django 4.1.5 on 2023-01-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('fname', models.CharField(help_text='First Name of Doctor', max_length=255, verbose_name='First Name')),
                ('lname', models.CharField(help_text='Last Name of Doctor', max_length=255, verbose_name='Last Name')),
                ('uname', models.CharField(help_text='Username of Doctor', max_length=255, primary_key=True, serialize=False, verbose_name='Username')),
                ('email', models.EmailField(help_text='eMail to contact you for notifications', max_length=254, verbose_name='eMail')),
                ('pwd', models.CharField(help_text='Password', max_length=255, verbose_name='Password')),
            ],
            options={
                'ordering': ['lname', 'fname'],
            },
        ),
        migrations.CreateModel(
            name='Pharmacist',
            fields=[
                ('fname', models.CharField(help_text='First Name of Doctor', max_length=255, verbose_name='First Name')),
                ('lname', models.CharField(help_text='Last Name of Doctor', max_length=255, verbose_name='Last Name')),
                ('uname', models.CharField(help_text='Username of Doctor', max_length=255, primary_key=True, serialize=False, verbose_name='Username')),
                ('clinic', models.CharField(help_text='First Name of Doctor', max_length=255, verbose_name='First Name')),
                ('email', models.EmailField(help_text='eMail to contact you for notifications', max_length=254, verbose_name='eMail')),
                ('pwd', models.CharField(help_text='Password', max_length=255, verbose_name='Password')),
            ],
            options={
                'ordering': ['lname', 'fname', 'clinic'],
            },
        ),
    ]
