# Generated by Django 4.1.5 on 2023-01-17 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountforms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pharmacist',
            options={'ordering': ['lname', 'fname', 'clinic']},
        ),
        migrations.AlterField(
            model_name='pharmacist',
            name='clinic',
            field=models.CharField(help_text='First Name of Doctor', max_length=255),
        ),
        migrations.AlterField(
            model_name='pharmacist',
            name='email',
            field=models.EmailField(help_text='eMail to contact you for notifications', max_length=254),
        ),
        migrations.AlterField(
            model_name='pharmacist',
            name='fname',
            field=models.CharField(help_text='First Name of Doctor', max_length=255),
        ),
        migrations.AlterField(
            model_name='pharmacist',
            name='lname',
            field=models.CharField(help_text='Last Name of Doctor', max_length=255),
        ),
        migrations.AlterField(
            model_name='pharmacist',
            name='pwd',
            field=models.CharField(help_text='Password', max_length=255),
        ),
        migrations.AlterField(
            model_name='pharmacist',
            name='uname',
            field=models.CharField(help_text='Username of Doctor', max_length=255, primary_key=True, serialize=False),
        ),
    ]
