# Generated by Django 4.1.5 on 2023-02-10 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountforms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pharmacist',
            options={'ordering': ['email', 'clinic']},
        ),
        migrations.RemoveField(
            model_name='account',
            name='puser',
        ),
        migrations.RemoveField(
            model_name='pharmacist',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='pharmacist',
            name='lname',
        ),
        migrations.RemoveField(
            model_name='pharmacist',
            name='pwd',
        ),
        migrations.RemoveField(
            model_name='pharmacist',
            name='uname',
        ),
        migrations.AddField(
            model_name='pharmacist',
            name='name',
            field=models.EmailField(blank=True, max_length=254, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='pharmacist',
            name='clinic',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='pharmacist',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True),
        ),
    ]
