# Generated by Django 4.1.5 on 2023-02-10 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountforms', '0002_alter_pharmacist_options_remove_account_puser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='puser',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accountforms.pharmacist'),
        ),
    ]
