# Generated by Django 4.1.5 on 2023-01-26 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountforms', '0002_alter_pharmacist_options_alter_pharmacist_clinic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='eMail'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='fname',
            field=models.CharField(max_length=255, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='lname',
            field=models.CharField(max_length=255, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='pwd',
            field=models.CharField(max_length=255, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='uname',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='pharmacist',
            name='clinic',
            field=models.CharField(max_length=255, verbose_name='Clinic'),
        ),
        migrations.AlterField(
            model_name='pharmacist',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='eMail'),
        ),
        migrations.AlterField(
            model_name='pharmacist',
            name='fname',
            field=models.CharField(max_length=255, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='pharmacist',
            name='lname',
            field=models.CharField(max_length=255, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='pharmacist',
            name='pwd',
            field=models.CharField(max_length=255, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='pharmacist',
            name='uname',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Username'),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='eMail')),
                ('uname', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Username')),
                ('password', models.CharField(max_length=255)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('duser', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accountforms.doctor')),
                ('puser', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accountforms.pharmacist')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
