# Generated by Django 4.1.5 on 2023-02-10 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountforms', '0003_account_puser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['email', 'doctorid']},
        ),
        migrations.RemoveField(
            model_name='account',
            name='duser',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='lname',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='pwd',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='uname',
        ),
        migrations.AddField(
            model_name='doctor',
            name='doctorid',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='doctor',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False, verbose_name='eMail'),
        ),
        migrations.AlterField(
            model_name='pharmacist',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='name'),
        ),
    ]
