# Generated by Django 4.1.5 on 2023-01-26 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountforms', '0003_alter_doctor_email_alter_doctor_fname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='uname',
            new_name='username',
        ),
    ]
