# Generated by Django 4.1.5 on 2023-02-12 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountforms', '0001_squashed_0007_alter_order_reciever'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True),
        ),
    ]
